# Generated by Django 2.1.5 on 2019-01-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10, unique=True)),
                ('aliases', models.CharField(max_length=10, null=True)),
                ('keyword', models.CharField(max_length=20, null=True)),
                ('label', models.CharField(max_length=10, null=True)),
                ('describle', models.CharField(max_length=50, null=True)),
                ('fnode', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=10, null=True)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
    ]
